# Generated by Django 3.1.6 on 2021-02-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_asset_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
