# Generated by Django 3.1.6 on 2021-05-29 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210204_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Office', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee'),
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.office'),
        ),
        migrations.AddField(
            model_name='employee',
            name='offic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.office'),
        ),
    ]
