# Generated by Django 3.1.6 on 2021-05-29 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210529_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='offic',
            new_name='office',
        ),
        migrations.AddField(
            model_name='department',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.office'),
        ),
    ]
